### ISSUE TITLE
MVP model development

### ISSUE THREAD

**Issue by judemin** [euphony-io/sound-helper#1]
## 초기 MVP 모델 아이디어
Java로 구현

### 환자 (Transmitter)
브로드캐스트 될 신원, 질병 정보 작성
다른 이용자가 특정 행위를 했을 때 브로드캐스트 되는 기능
- 신원 : 이름 , 나이, 비상 연락망

### 일반 이용자 (Listener)
브로드캐스트 되는 단말기에 가져다 대면 정보 띄워주기

## 액티비티 및 기능 도식화
![도식화](https://user-images.githubusercontent.com/20484492/129515610-89722dbc-c3b5-47a2-9b57-6de1efbbf001.PNG)

## 역할분담
메인페이지 – 옥은진
정보작성 – 김미소
리스너 – 박준규
트랜스미터 처리 – 민상연

**Comment by judemin** [comment]
역할분담
메인페이지 – 옥은진
정보작성 – 김미소
리스너 – 박준규
트랜스미터 처리 – 민상연

**Comment by kmsaidev** [comment]
### I'm almost done with the information entry page. I set the style randomly, but I think it's a little fancy, so I'm going to change it. Please advise in terms of style properties and functionality. 
Also, I want to know about the language that the application will provide. I don't know yet, so I used both Korean and English in the application UI.

## Information Entry Main Page
<img src ="https://user-images.githubusercontent.com/88221290/129604114-85abd870-f925-46d3-9ed2-0e5b99fd90ae.png" width="300" height="500"></img>
## Page when you press the Date of Birth button
<img src ="https://user-images.githubusercontent.com/88221290/129604551-034ace63-b13a-4876-9e26-02a8c31243c7.png" width="300" height="500"></img>
## Select chronic disease page
<img src ="https://user-images.githubusercontent.com/88221290/129604655-4ed14d31-1523-4ed2-860c-7687f9fe543b.png" width="300" height="500"></img>
## Page when Other(기타) was selected for chronic disease selection
<img src ="https://user-images.githubusercontent.com/88221290/129604952-73f0d7ea-2e34-4a1a-816e-936215239e25.png"
width="300" height="500"></img>
## Verify that the data I entered is saved well
![check](https://user-images.githubusercontent.com/88221290/129605215-4f9bd148-a5c2-422f-87f1-0e9bb7bb9d47.png)

**Comment by judemin** [comment]
> ### I'm almost done drafting the information entry page. I set the style randomly, but I think it's a little fancy, so I'm going to change it. Please advise in terms of style properties and functionality.
> Also, I want to know about the language that the application will provide. I don't know yet, so I used both Korean and English in the application UI.
> 
> ## Information Entry Main Page
> <img alt="" width="300" height="500" src="https://user-images.githubusercontent.com/88221290/129604114-85abd870-f925-46d3-9ed2-0e5b99fd90ae.png">
> 
> ## Page when you press the Date of Birth button
> <img alt="" width="300" height="500" src="https://user-images.githubusercontent.com/88221290/129604551-034ace63-b13a-4876-9e26-02a8c31243c7.png">
> 
> ## Select chronic disease page
> <img alt="" width="300" height="500" src="https://user-images.githubusercontent.com/88221290/129604655-4ed14d31-1523-4ed2-860c-7687f9fe543b.png">
> 
> ## Page when Other(기타) was selected for chronic disease selection
> <img alt="" width="300" height="500" src="https://user-images.githubusercontent.com/88221290/129604952-73f0d7ea-2e34-4a1a-816e-936215239e25.png">
> 
> ## Verify that the data I entered is saved well
> ![check](https://user-images.githubusercontent.com/88221290/129605215-4f9bd148-a5c2-422f-87f1-0e9bb7bb9d47.png)

Nice work! Otherwise, I think we should talk about the structure of parsed data.
ex)
Encode : name;date;phonenum;info
Decode : Parse string with token ';'

We might talk about style in #5

**Comment by kmsaidev** [comment]
> > ### I'm almost done drafting the information entry page. I set the style randomly, but I think it's a little fancy, so I'm going to change it. Please advise in terms of style properties and functionality.
> > Also, I want to know about the language that the application will provide. I don't know yet, so I used both Korean and English in the application UI.
> 
> Nice work! Otherwise, I think we should talk about the structure of parsed data.
> ex)
> Encode : name;date;phonenum;info
> Decode : Parse string with token ';'
> 
> We might talk about style in #5

That's right. Think about it and comment on the issue.

**Comment by judemin** [comment]
Successfully created TransmitActivity class and xml design layout.
With the sensor, the listener device detects shake by gravitational acceleration.
It controls (stops and resumes) sensor manager and sound manager to improve the application's performance.
Users can stop broadcasting simply by touch the button.

![result](https://user-images.githubusercontent.com/20484492/129672865-22cef436-4b5e-423f-a7f8-306ea45efdce.jpg)

Let's discuss about color and size of elements in issue #5

**Comment by kmsaidev** [comment]
> Successfully created TransmitActivity class and xml design layout.
> 
> With the sensor, the listener device detects shake by gravitational acceleration.
> 
> It controls (stops and resumes) sensor manager and sound manager to improve the application's performance.
> 
> Users can stop broadcasting by touching the button.
> 
> 
> 
> ![result](https://user-images.githubusercontent.com/20484492/129672865-22cef436-4b5e-423f-a7f8-306ea45efdce.jpg)
> 
> 
> 
> Let's discuss the color and size of elements in issue #5 

I like it. Thank you for your hard work.

**Comment by judemin** [comment]
Since successfully merging a pull request may close the issue,
I think we should link PR creafully.

**Comment by judemin** [comment]
Successfully received data from InfoActivity.

![KakaoTalk_20210820_200540072](https://user-images.githubusercontent.com/20484492/130224747-af3d196d-d543-4303-9be7-7a16b6005bf0.jpg)
