### ISSUE TITLE
MVP model layout design

### ISSUE THREAD

**Issue by judemin** [euphony-io/sound-helper#5]
## MVP 모델의 각 액티비티에 대한 레이아웃 디자인
버튼이나 메뉴바 등의 UI 디자인은 따로 Issue를 생성해서 협업

### Main activity
![슬라이드2](https://user-images.githubusercontent.com/20484492/129516964-d14571f5-c755-4938-9b70-fbbf89e8b623.PNG)

### Info input activity
![슬라이드3](https://user-images.githubusercontent.com/20484492/129517148-abb95db2-0faa-41c0-bcd6-738a55c8b098.PNG)

### Listener activity
![슬라이드4](https://user-images.githubusercontent.com/20484492/129517152-2181e4c6-3ff5-4a0b-ad0c-caa2968a8bc8.PNG)

### Transmitter activity
![슬라이드5](https://user-images.githubusercontent.com/20484492/129517158-b553bdda-36c8-44c3-9b13-1a4aa96394e3.PNG)

### Color palette
https://colorhunt.co/palette/fcd1d1ece2e1d3e0dcaee1e1

**Comment by kmsaidev** [comment]
https://colorhunt.co/palette/fcd1d1ece2e1d3e0dcaee1e1

This is the color format we discussed earlier.

**Comment by kmsaidev** [comment]
> https://colorhunt.co/palette/fcd1d1ece2e1d3e0dcaee1e1
> 
> This is the color format we discussed earlier.

It would be good to use the pink color at the top of this format for the title part of the top application.

**Comment by kmsaidev** [comment]
> > https://colorhunt.co/palette/fcd1d1ece2e1d3e0dcaee1e1
> > This is the color format we discussed earlier.
> 
> It would be good to use the pink color at the top of this format for the title part of the top application.

Like this!
![Screenshot_1629097256](https://user-images.githubusercontent.com/88221290/129524155-a30a34f0-de4a-474b-b346-0eec16248ecd.png)

**Comment by kuro11pow2** [comment]
> > > https://colorhunt.co/palette/fcd1d1ece2e1d3e0dcaee1e1
> > > This is the color format we discussed earlier.
> > 
> > 
> > It would be good to use the pink color at the top of this format for the title part of the top application.
> 
> Like this!

WOW I like that! 

![chrome_6oq1GHxvFZ](https://user-images.githubusercontent.com/47289893/129553839-68d56b6f-2dd1-4060-ae91-33efa9a07e55.png)

How about adding this four colors to our resources? 

**res/values/colors.xml**
```xml
<?xml version="1.0" encoding="utf-8"?>
<resources>
   <color name="pastel_pink">#FCD1D1</color>
   <color name="light_pastel_pink">#ECE2E1</color>
   <color name="light_mint">#D3E0DC</color>
   <color name="light_turquoise">#AEE1E1</color>
</resources>
```

**Comment by kmsaidev** [comment]
> > > > https://colorhunt.co/palette/fcd1d1ece2e1d3e0dcaee1e1
> 
> > > > This is the color format we discussed earlier.
> 
> > > 
> 
> > > 
> 
> > > It would be good to use the pink color at the top of this format for the title part of the top application.
> 
> > 
> 
> > Like this!
> 
> 
> 
> WOW I like that! 
> 
> 
> 
> ![chrome_6oq1GHxvFZ](https://user-images.githubusercontent.com/47289893/129553839-68d56b6f-2dd1-4060-ae91-33efa9a07e55.png)
> 
> 
> 
> How about adding this four colors to our resources? 
> 
> 
> 
> **res/values/colors.xml**
> 
> ```xml
> 
> <?xml version="1.0" encoding="utf-8"?>
> 
> <resources>
> 
>    <color name="pastel_pink">#FCD1D1</color>
> 
>    <color name="light_pastel_pink">#ECE2E1</color>
> 
>    <color name="light_mint">#D3E0DC</color>
> 
>    <color name="light_turquoise">#AEE1E1</color>
> 
> </resources>
> 
> ```

All right. I think it would be good to use it properly.

**Comment by judemin** [comment]
How do you think about using only two colors in the palette for accent and use white and black (gray) for buttons and TextView?

**Comment by kmsaidev** [comment]
> How do you think about using only two colors in the palette for accent and use white and black (gray) for buttons and TextView?

Good. I think it looked a bit messy with the color template we used at first. I think something simple would be good.

**Comment by kmsaidev** [comment]
I just changed the color. Are you all right?
<img src = "https://user-images.githubusercontent.com/88221290/129661084-29ebd5b7-968c-47d2-9208-cddd4b9e14d6.png" width = "300" height = "500"></img>

**Comment by eunzinn** [comment]
I made it like this for now, but I think it's okay to use these two colors(pink, grey).

<img src ="https://user-images.githubusercontent.com/88362254/129715022-6ab3c3de-12a9-4932-a194-00b86f6ecbdc.png" width="400" height="700">

**Comment by kuro11pow2** [comment]
> I made it like this for now, but I think it's okay to use these two colors(pink, grey).

This is what I wanted.

**Comment by kuro11pow2** [comment]
![Screenshot_2021-08-18-00-01-54-228_com eutophia sound_helper](https://user-images.githubusercontent.com/47289893/129751081-affb6668-a626-4395-9536-40f0555e7a0a.jpg)

How about this color? I tried the color of blood that symbolizes saving lives. Like the Red Cross.

**Comment by kmsaidev** [comment]
> ![Screenshot_2021-08-18-00-01-54-228_com eutophia sound_helper](https://user-images.githubusercontent.com/47289893/129751081-affb6668-a626-4395-9536-40f0555e7a0a.jpg)
> 
> 
> 
> How about this color? I tried the color of blood that symbolizes saving lives. Like the Red Cross.

It looks good. Let's talk again at the meeting on Thursday!

**Comment by judemin** [comment]
> How about this color? I tried the color of blood that symbolizes saving lives. Like the Red Cross.

Can you send me hex codes of red and gray color?

**Comment by kuro11pow2** [comment]
> > How about this color? I tried the color of blood that symbolizes saving lives. Like the Red Cross.
> 
> Can you send me hex codes of red and gray color?

Here are the colors!

```xml
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <color name="purple_200">#FFBB86FC</color>
    <color name="purple_500">#FF6200EE</color>
    <color name="purple_700">#FF3700B3</color>
    <color name="teal_200">#FF03DAC5</color>
    <color name="teal_700">#FF018786</color>
    <color name="black">#FF000000</color>
    <color name="white">#FFFFFFFF</color>

    <color name="bloody_red">#CB4335</color>
    <color name="light_bloody_red">#F1948A</color>
    <color name="light_mint">#D3E0DC</color>
    <color name="light_turquoise">#AEE1E1</color>
</resources>
```
